'use strict';
const cloneDefault=()=>JSON.parse(JSON.stringify(DEFAULT_STATE));
function loadState(){try{const raw=JSON.parse(localStorage.getItem('rutaJulioV2')||'null')||JSON.parse(localStorage.getItem('rutaJulio')||'null');return sanitizeState(raw)}catch{return cloneDefault()}}
function sanitizeState(raw){const out=cloneDefault();if(!raw||typeof raw!=='object')return out;out.diag=raw.diag&&typeof raw.diag==='object'?raw.diag:{};out.mods=raw.mods&&typeof raw.mods==='object'?raw.mods:{};out.reviewHard=raw.reviewHard&&typeof raw.reviewHard==='object'?raw.reviewHard:{};out.prefs={...out.prefs,...(raw.prefs&&typeof raw.prefs==='object'?raw.prefs:{})};out.lastView=typeof raw.lastView==='string'?raw.lastView:'home';out.version=2;return out}
let S=loadState();
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const byId=id=>document.getElementById(id);
function save(){localStorage.setItem('rutaJulioV2',JSON.stringify(S));updateBackupText()}
function toast(msg){const t=byId('toast');t.textContent=msg;t.classList.add('show');clearTimeout(toast._h);toast._h=setTimeout(()=>t.classList.remove('show'),2600)}
function view(id){if(!byId(id))return;$$('.view').forEach(v=>v.classList.toggle('active',v.id===id));$$('#nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===id));S.lastView=id;save();window.scrollTo(0,0);if(id==='mods')renderModules()}
function diagCount(){return Object.values(S.diag).filter(Boolean).length}
function routeKey(){const n=diagCount();return n<4?'foundations':n<8?'bridge':'applied'}
function route(){return ROUTES[routeKey()]}
function recommendedIndices(){const done=S.mods;const hard=Object.entries(S.reviewHard).filter(([,v])=>v).map(([i])=>REVIEW_TO_MODULE[Number(i)]).filter(i=>Number.isInteger(i)&&!done[i]);const order=[...new Set([...hard,...route().order])];const undone=order.filter(i=>!done[i]);return undone.slice(0,3)}
function nextTarget(){if(Object.keys(S.diag).length<3)return{kind:'diag',title:'diagnóstico',reason:'Primero necesito una señal mínima de qué ya dominas.'};const rec=recommendedIndices();if(rec.length)return{kind:'module',index:rec[0],title:M[rec[0]][0],reason:'Es el siguiente paso de mayor retorno según tu diagnóstico actual.'};return{kind:'proof',title:'portfolio',reason:'Ya marcaste todos los módulos: convierte el dominio en evidencia verificable.'}}
function progress(){const n=Object.values(S.mods).filter(Boolean).length,p=Math.round(n/M.length*100);byId('homeBar').style.width=p+'%';byId('homeProgress').textContent=`${p}% dominado · ${n}/${M.length}`;const next=nextTarget();byId('nextTitle').textContent=next.title;byId('nextReason').textContent=next.reason;byId('nextBtn').onclick=()=>{if(next.kind==='module'){view('mods');setTimeout(()=>openModule(next.index),80)}else view(next.kind)}}
function renderDiagnostics(){const wrap=byId('diagnostics');wrap.innerHTML=D.map((d,i)=>`<label class="diag"><input type="checkbox" data-diag="${i}" ${S.diag[i]?'checked':''}><span><b>${i+1}. ${d[0]}</b><span>${d[1]}</span></span></label>`).join('');$$('[data-diag]').forEach(el=>el.addEventListener('change',()=>{S.diag[el.dataset.diag]=el.checked;save();updateDiagnosis();renderModules();progress()}));updateDiagnosis()}
function updateDiagnosis(){const n=diagCount(),r=route();byId('score').textContent=`${n}/10`;byId('levelName').textContent=r.name;let title,msg;if(n<4){title='Empezar por comprensión y debugging.';msg='La prioridad es ganar fluidez con código pequeño, sin quitarte la IA de golpe.'}else if(n<8){title='Cerrar huecos con proyectos reales.';msg='Ya puedes acelerar: APIs, debugging, testing y automatización primero; fundamentos sólo donde hagan falta.'}else{title='Convertir comprensión en evidencia.';msg='Tu ruta debe parecerse más al trabajo: tests, integración, backend pequeño y defensa de decisiones.'}byId('diagTitle').textContent=title;byId('diagMessage').textContent=msg;byId('routeHeadline').textContent=r.headline;byId('routeText').textContent=r.text}
function renderModules(){const rec=new Set(recommendedIndices());const wrap=byId('modules');wrap.innerHTML=M.map((m,i)=>`<article class="module ${S.mods[i]?'done':''} ${rec.has(i)?'recommended':''}">${rec.has(i)?'<span class="recflag">prioridad</span>':''}<div><div class="num">${String(i+1).padStart(2,'0')}</div><h3>${m[0]}</h3><p>${m[1]}</p></div><div class="opts"><label class="donecheck"><input type="checkbox" data-mod="${i}" ${S.mods[i]?'checked':''}> dominado</label><button class="open" data-open="${i}">abrir</button></div></article>`).join('');$$('[data-mod]').forEach(el=>el.addEventListener('change',()=>{S.mods[el.dataset.mod]=el.checked;save();renderModules();progress()}));$$('[data-open]').forEach(el=>el.addEventListener('click',()=>openModule(+el.dataset.open)));updateDiagnosis()}
function openModule(i){const m=M[i],mode=S.prefs.sessionMode||'solo';byId('sheetContent').innerHTML=`<div class="ey">módulo ${String(i+1).padStart(2,'0')} · modo ${mode==='solo'?'intento propio':mode==='hint'?'con pista':'con IA verificable'}</div><h2 id="lessonTitle">${m[0]}</h2><p>${m[1]}</p><div class="lesson"><b>Modelo mental</b><p>${m[2]}</p><button class="speak" data-speak>leer</button></div><div class="lesson"><b>Reto</b><p>${m[3]}</p><button class="hintbtn" data-hint>necesito una pista</button><div class="hint">${m[5]}</div></div><div class="lesson"><b>Puerta de dominio</b><p>${m[4]}</p></div><div class="lesson"><b>Uso de IA recomendado</b><p>${mode==='solo'?'Haz primero 10–15 minutos sin respuesta completa. Puedes consultar sintaxis puntual.':mode==='hint'?'Pide una pista o explicación parcial, no la solución terminada.':'Puedes usar IA desde el inicio, pero pide cambios pequeños y verifica con tests, ejecución o documentación.'}</p></div>`;byId('dialog').classList.add('open');document.body.style.overflow='hidden';const hint=byId('sheetContent').querySelector('[data-hint]');hint.addEventListener('click',()=>{hint.nextElementSibling.classList.toggle('show');hint.textContent=hint.nextElementSibling.classList.contains('show')?'ocultar pista':'necesito una pista'});const speak=byId('sheetContent').querySelector('[data-speak]');speak.addEventListener('click',()=>speakLesson(m[2]))}
function closeDialog(){byId('dialog').classList.remove('open');document.body.style.overflow=''}
function speakLesson(text){if(!('speechSynthesis'in window)){toast('Lectura en voz alta no disponible en este navegador.');return}speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='es-MX';u.rate=.95;speechSynthesis.speak(u);toast('Leyendo el modelo mental.')}
function renderReviews(){const wrap=byId('reviews');wrap.innerHTML=R.map((r,i)=>`<article class="review"><b>${r[0]}</b><div class="answer">${r[1]}</div><button data-reveal="${i}">revelar</button><button data-hard="${i}" class="ghost">${S.reviewHard[i]?'marcado difícil':'me costó'}</button></article>`).join('');$$('[data-reveal]').forEach(el=>el.addEventListener('click',()=>{const card=el.closest('.review');card.classList.toggle('show');el.textContent=card.classList.contains('show')?'ocultar':'revelar'}));$$('[data-hard]').forEach(el=>el.addEventListener('click',()=>{const i=el.dataset.hard;S.reviewHard[i]=!S.reviewHard[i];save();renderReviews();toast(S.reviewHard[i]?'Lo priorizaré en tu repaso.':'Quitado de difíciles.')}))}
function applyPrefs(){document.body.classList.toggle('dark',!!S.prefs.dark);document.body.classList.toggle('wide',!!S.prefs.wide);document.body.classList.toggle('focus',!!S.prefs.focus);document.documentElement.style.setProperty('--fs',(Number(S.prefs.fs)||16)+'px');$$('[data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode===(S.prefs.sessionMode||'solo')));const labels={solo:'intento propio',hint:'con pista',ai:'IA verificable'};byId('modeLabel').textContent=labels[S.prefs.sessionMode]||labels.solo}
let seconds=900,timerHandle=null,timerRunning=false;
function drawTimer(){const m=Math.floor(seconds/60),s=seconds%60;byId('timer').textContent=`${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`}
function toggleTimer(){if(timerRunning){clearInterval(timerHandle);timerRunning=false;byId('timerStart').textContent='continuar';return}timerRunning=true;byId('timerStart').textContent='pausar';timerHandle=setInterval(()=>{seconds=Math.max(0,seconds-1);drawTimer();if(seconds===0){clearInterval(timerHandle);timerRunning=false;byId('timerStart').textContent='iniciar';toast('Sesión terminada. Escribe qué terminaste antes de seguir.')}},1000)}
function resetTimer(){clearInterval(timerHandle);timerRunning=false;seconds=900;byId('timerStart').textContent='iniciar';drawTimer()}
function backupObject(){return{app:'ruta-julio',exportedAt:new Date().toISOString(),state:S}}
function updateBackupText(){const ta=byId('backupText');if(ta)ta.value=JSON.stringify(backupObject(),null,2)}
function exportBackup(){const blob=new Blob([JSON.stringify(backupObject(),null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`ruta-julio-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),500);toast('Respaldo descargado.')}
async function copyBackup(){const text=JSON.stringify(backupObject(),null,2);try{await navigator.clipboard.writeText(text);toast('Respaldo copiado.')}catch{byId('backupText').focus();byId('backupText').select();toast('No pude usar el portapapeles; el JSON quedó seleccionado.')}}
async function importBackup(){const f=byId('importFile').files[0];if(!f){toast('Selecciona un archivo JSON primero.');return}try{const obj=JSON.parse(await f.text());const candidate=obj&&obj.app==='ruta-julio'?obj.state:obj;S=sanitizeState(candidate);save();applyPrefs();renderDiagnostics();renderModules();renderReviews();progress();toast('Progreso importado correctamente.')}catch{toast('Ese archivo no parece un respaldo válido.')}}
function resetAll(){if(!confirm('¿Reiniciar diagnóstico, módulos y preferencias? Esta acción no se puede deshacer.'))return;S=cloneDefault();save();applyPrefs();renderDiagnostics();renderModules();renderReviews();progress();view('home');toast('Curso reiniciado.')}
$$('[data-view]').forEach(b=>b.addEventListener('click',()=>view(b.dataset.view)));
$$('[data-go]').forEach(b=>b.addEventListener('click',()=>view(b.dataset.go)));
byId('diagToRoute').addEventListener('click',()=>view('mods'));
byId('closeDialog').addEventListener('click',closeDialog);byId('dialog').addEventListener('click',e=>{if(e.target===byId('dialog'))closeDialog()});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeDialog()});
byId('themeBtn').addEventListener('click',()=>{S.prefs.dark=!S.prefs.dark;save();applyPrefs()});
byId('spaceBtn').addEventListener('click',()=>{S.prefs.wide=!S.prefs.wide;save();applyPrefs()});
byId('focusBtn').addEventListener('click',()=>{S.prefs.focus=!S.prefs.focus;save();applyPrefs();toast(S.prefs.focus?'Modo enfoque activado.':'Modo enfoque desactivado.')});
byId('fontBtn').addEventListener('click',()=>{const cur=Number(S.prefs.fs)||16;S.prefs.fs=cur>=22?16:cur+2;save();applyPrefs();toast(`Texto: ${S.prefs.fs}px`)});
$$('[data-mode]').forEach(b=>b.addEventListener('click',()=>{S.prefs.sessionMode=b.dataset.mode;save();applyPrefs();toast(`Modo: ${byId('modeLabel').textContent}`)}));
byId('timerStart').addEventListener('click',toggleTimer);byId('timerReset').addEventListener('click',resetTimer);
byId('exportBtn').addEventListener('click',exportBackup);byId('copyBtn').addEventListener('click',copyBackup);byId('importBtn').addEventListener('click',importBackup);byId('resetAll').addEventListener('click',resetAll);
renderDiagnostics();renderModules();renderReviews();applyPrefs();progress();drawTimer();updateBackupText();
if(['home','diag','mods','review','proof','jobs','data'].includes(S.lastView))view(S.lastView);
