'use strict';
const cloneDefault=()=>JSON.parse(JSON.stringify(DEFAULT_STATE));
const SYNC_CONFIG_KEY='rutaJulioSyncV1';
let syncReady=false,syncPulling=false,syncTimer=null,audioUrl=null;
function loadState(){try{const raw=JSON.parse(localStorage.getItem('rutaJulioV2')||'null')||JSON.parse(localStorage.getItem('rutaJulio')||'null');return sanitizeState(raw)}catch{return cloneDefault()}}
function sanitizeState(raw){const out=cloneDefault();if(!raw||typeof raw!=='object')return out;out.diag=raw.diag&&typeof raw.diag==='object'?raw.diag:{};out.mods=raw.mods&&typeof raw.mods==='object'?raw.mods:{};out.reviewHard=raw.reviewHard&&typeof raw.reviewHard==='object'?raw.reviewHard:{};out.prefs={...out.prefs,...(raw.prefs&&typeof raw.prefs==='object'?raw.prefs:{})};out.lastView=typeof raw.lastView==='string'?raw.lastView:'home';out.version=3;return out}
function loadSyncConfig(){try{return JSON.parse(localStorage.getItem(SYNC_CONFIG_KEY)||'{}')}catch{return{}}}
let S=loadState(),syncCfg=loadSyncConfig();
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const byId=id=>document.getElementById(id);
function save(schedule=true){localStorage.setItem('rutaJulioV2',JSON.stringify(S));updateBackupText();if(schedule&&syncReady&&!syncPulling)scheduleSync()}
function toast(msg){const t=byId('toast');t.textContent=msg;t.classList.add('show');clearTimeout(toast._h);toast._h=setTimeout(()=>t.classList.remove('show'),3000)}
function view(id){if(!byId(id))return;$$('.view').forEach(v=>v.classList.toggle('active',v.id===id));$$('#nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===id));S.lastView=id;save();window.scrollTo(0,0);if(id==='mods')renderModules()}
function diagCount(){return Object.values(S.diag).filter(Boolean).length}
function routeKey(){const n=diagCount();return n<4?'foundations':n<8?'bridge':'applied'}
function route(){return ROUTES[routeKey()]}
function recommendedIndices(){const done=S.mods;const hard=Object.entries(S.reviewHard).filter(([,v])=>v).map(([i])=>REVIEW_TO_MODULE[Number(i)]).filter(i=>Number.isInteger(i)&&!done[i]);const order=[...new Set([...hard,...route().order])];return order.filter(i=>!done[i]).slice(0,3)}
function nextTarget(){if(Object.keys(S.diag).length<3)return{kind:'diag',title:'diagnóstico',reason:'Primero necesito una señal mínima de qué ya dominas.'};const rec=recommendedIndices();if(rec.length)return{kind:'module',index:rec[0],title:M[rec[0]][0],reason:'Es el siguiente paso de mayor retorno según tu diagnóstico actual.'};return{kind:'proof',title:'portfolio',reason:'Ya marcaste todos los módulos: convierte el dominio en evidencia verificable.'}}
function progress(){const n=Object.values(S.mods).filter(Boolean).length,p=Math.round(n/M.length*100);byId('homeBar').style.width=p+'%';byId('homeProgress').textContent=`${p}% dominado · ${n}/${M.length}`;const next=nextTarget();byId('nextTitle').textContent=next.title;byId('nextReason').textContent=next.reason;byId('nextBtn').onclick=()=>{if(next.kind==='module'){view('mods');setTimeout(()=>openModule(next.index),80)}else view(next.kind)}}
function renderDiagnostics(){const wrap=byId('diagnostics');wrap.innerHTML=D.map((d,i)=>`<label class="diag"><input type="checkbox" data-diag="${i}" ${S.diag[i]?'checked':''}><span><b>${i+1}. ${d[0]}</b><span>${d[1]}</span></span></label>`).join('');$$('[data-diag]').forEach(el=>el.addEventListener('change',()=>{S.diag[el.dataset.diag]=el.checked;save();updateDiagnosis();renderModules();progress()}));updateDiagnosis()}
function updateDiagnosis(){const n=diagCount(),r=route();byId('score').textContent=`${n}/10`;byId('levelName').textContent=r.name;let title,msg;if(n<4){title='Empezar por comprensión y debugging.';msg='La prioridad es ganar fluidez con código pequeño, sin quitarte la IA de golpe.'}else if(n<8){title='Cerrar huecos con proyectos reales.';msg='Ya puedes acelerar: APIs, debugging, testing y automatización primero; fundamentos sólo donde hagan falta.'}else{title='Convertir comprensión en evidencia.';msg='Tu ruta debe parecerse más al trabajo: tests, integración, backend pequeño y defensa de decisiones.'}byId('diagTitle').textContent=title;byId('diagMessage').textContent=msg;byId('routeHeadline').textContent=r.headline;byId('routeText').textContent=r.text}
function renderModules(){const rec=new Set(recommendedIndices());const wrap=byId('modules');wrap.innerHTML=M.map((m,i)=>`<article class="module ${S.mods[i]?'done':''} ${rec.has(i)?'recommended':''}">${rec.has(i)?'<span class="recflag">prioridad</span>':''}<div><div class="num">${String(i+1).padStart(2,'0')}</div><h3>${m[0]}</h3><p>${m[1]}</p></div><div class="opts"><label class="donecheck"><input type="checkbox" data-mod="${i}" ${S.mods[i]?'checked':''}> dominado</label><button class="open" data-open="${i}">abrir</button></div></article>`).join('');$$('[data-mod]').forEach(el=>el.addEventListener('change',()=>{S.mods[el.dataset.mod]=el.checked;save();renderModules();progress()}));$$('[data-open]').forEach(el=>el.addEventListener('click',()=>openModule(+el.dataset.open)));updateDiagnosis()}
function openModule(i){const m=M[i],mode=S.prefs.sessionMode||'solo';byId('sheetContent').innerHTML=`<div class="ey">módulo ${String(i+1).padStart(2,'0')} · modo ${mode==='solo'?'intento propio':mode==='hint'?'con pista':'con IA verificable'}</div><h2 id="lessonTitle">${m[0]}</h2><p>${m[1]}</p><div class="lesson"><b>Modelo mental</b><p>${m[2]}</p><div class="actions"><button class="speak" data-audio>audio del servidor</button><button class="ghost" data-speak>voz del navegador</button></div><audio data-player controls hidden style="width:100%;margin-top:10px"></audio><small data-audio-status></small></div><div class="lesson"><b>Reto</b><p>${m[3]}</p><button class="hintbtn" data-hint>necesito una pista</button><div class="hint">${m[5]}</div></div><div class="lesson"><b>Puerta de dominio</b><p>${m[4]}</p></div><div class="lesson"><b>Uso de IA recomendado</b><p>${mode==='solo'?'Haz primero 10–15 minutos sin respuesta completa. Puedes consultar sintaxis puntual.':mode==='hint'?'Pide una pista o explicación parcial, no la solución terminada.':'Puedes usar IA desde el inicio, pero pide cambios pequeños y verifica con tests, ejecución o documentación.'}</p></div>`;byId('dialog').classList.add('open');document.body.style.overflow='hidden';const hint=byId('sheetContent').querySelector('[data-hint]');hint.addEventListener('click',()=>{hint.nextElementSibling.classList.toggle('show');hint.textContent=hint.nextElementSibling.classList.contains('show')?'ocultar pista':'necesito una pista'});byId('sheetContent').querySelector('[data-speak]').addEventListener('click',()=>speakBrowser(m[2]));byId('sheetContent').querySelector('[data-audio]').addEventListener('click',e=>serverAudio(m[2],e.currentTarget))}
function closeDialog(){byId('dialog').classList.remove('open');document.body.style.overflow='';if(audioUrl){URL.revokeObjectURL(audioUrl);audioUrl=null}}
function speakBrowser(text){if(!('speechSynthesis'in window)){toast('La voz del navegador no está disponible aquí. Usa audio del servidor.');return}try{speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='es-MX';u.rate=.95;u.onerror=()=>toast('Brave no pudo reproducir esta voz. Usa audio del servidor.');speechSynthesis.speak(u);toast('Intentando voz del navegador.')}catch{toast('Brave bloqueó la voz del navegador. Usa audio del servidor.')}}
function normalizedApiUrl(){return String(syncCfg.url||'').trim().replace(/\/+$/,'')}
function authHeaders(extra={}){return{...extra,Authorization:`Bearer ${syncCfg.token||''}`}}
async function serverAudio(text,button){const player=byId('sheetContent').querySelector('[data-player]'),status=byId('sheetContent').querySelector('[data-audio-status]');if(!normalizedApiUrl()||!syncCfg.token){status.textContent='Configura el VPS en la sección datos para usar esta alternativa.';viewAfterDialog('data');return}button.disabled=true;status.textContent='Generando audio…';try{const res=await fetch(`${normalizedApiUrl()}/v1/tts`,{method:'POST',headers:authHeaders({'Content-Type':'application/json'}),body:JSON.stringify({text})});if(!res.ok)throw new Error(`HTTP ${res.status}`);const blob=await res.blob();if(audioUrl)URL.revokeObjectURL(audioUrl);audioUrl=URL.createObjectURL(blob);player.src=audioUrl;player.hidden=false;status.textContent='Audio listo. Si Brave no lo inicia automáticamente, toca ▶.';try{await player.play()}catch{} }catch(err){status.textContent='No pude generar audio en el servidor. Revisa la conexión en datos.';toast('Audio del servidor no disponible.')}finally{button.disabled=false}}
function viewAfterDialog(id){setTimeout(()=>{closeDialog();view(id)},500)}
function renderReviews(){const wrap=byId('reviews');wrap.innerHTML=R.map((r,i)=>`<article class="review"><b>${r[0]}</b><div class="answer">${r[1]}</div><button data-reveal="${i}">revelar</button><button data-hard="${i}" class="ghost">${S.reviewHard[i]?'marcado difícil':'me costó'}</button></article>`).join('');$$('[data-reveal]').forEach(el=>el.addEventListener('click',()=>{const card=el.closest('.review');card.classList.toggle('show');el.textContent=card.classList.contains('show')?'ocultar':'revelar'}));$$('[data-hard]').forEach(el=>el.addEventListener('click',()=>{const i=el.dataset.hard;S.reviewHard[i]=!S.reviewHard[i];save();renderReviews();progress();toast(S.reviewHard[i]?'Lo priorizaré en tu repaso.':'Quitado de difíciles.')}))}
function applyPrefs(){document.body.classList.toggle('dark',!!S.prefs.dark);document.body.classList.toggle('wide',!!S.prefs.wide);document.body.classList.toggle('focus',!!S.prefs.focus);document.documentElement.style.setProperty('--fs',(Number(S.prefs.fs)||16)+'px');$$('[data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode===(S.prefs.sessionMode||'solo')));const labels={solo:'intento propio',hint:'con pista',ai:'IA verificable'};byId('modeLabel').textContent=labels[S.prefs.sessionMode]||labels.solo}
let seconds=900,timerHandle=null,timerRunning=false;
function drawTimer(){const m=Math.floor(seconds/60),s=seconds%60;byId('timer').textContent=`${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`}
function toggleTimer(){if(timerRunning){clearInterval(timerHandle);timerRunning=false;byId('timerStart').textContent='continuar';return}timerRunning=true;byId('timerStart').textContent='pausar';timerHandle=setInterval(()=>{seconds=Math.max(0,seconds-1);drawTimer();if(seconds===0){clearInterval(timerHandle);timerRunning=false;byId('timerStart').textContent='iniciar';toast('Sesión terminada. Escribe qué terminaste antes de seguir.')}},1000)}
function resetTimer(){clearInterval(timerHandle);timerRunning=false;seconds=900;byId('timerStart').textContent='iniciar';drawTimer()}
function backupObject(){return{app:'ruta-julio',exportedAt:new Date().toISOString(),state:S}}
function updateBackupText(){const ta=byId('backupText');if(ta)ta.value=JSON.stringify(backupObject(),null,2)}
function exportBackup(){const blob=new Blob([JSON.stringify(backupObject(),null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`ruta-julio-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),500);toast('Respaldo descargado.')}
async function copyBackup(){const text=JSON.stringify(backupObject(),null,2);try{await navigator.clipboard.writeText(text);toast('Respaldo copiado.')}catch{byId('backupText').focus();byId('backupText').select();toast('No pude usar el portapapeles; el JSON quedó seleccionado.')}}
async function importBackup(){const f=byId('importFile').files[0];if(!f){toast('Selecciona un archivo JSON primero.');return}try{const obj=JSON.parse(await f.text());const candidate=obj&&obj.app==='ruta-julio'?obj.state:obj;const prefs=S.prefs;S=sanitizeState(candidate);S.prefs=prefs;save();applyPrefs();renderDiagnostics();renderModules();renderReviews();progress();toast('Progreso importado correctamente.')}catch{toast('Ese archivo no parece un respaldo válido.')}}
function resetAll(){if(!confirm('¿Reiniciar diagnóstico y módulos? Las preferencias de este dispositivo se conservarán.'))return;const prefs=S.prefs;S=cloneDefault();S.prefs=prefs;save();renderDiagnostics();renderModules();renderReviews();progress();view('home');toast('Progreso reiniciado.')}
function syncState(){return{version:3,diag:S.diag,mods:S.mods,reviewHard:S.reviewHard,lastView:S.lastView}}
function applyRemoteProgress(remote){if(!remote||typeof remote!=='object')return;syncPulling=true;S.diag=remote.diag&&typeof remote.diag==='object'?remote.diag:{};S.mods=remote.mods&&typeof remote.mods==='object'?remote.mods:{};S.reviewHard=remote.reviewHard&&typeof remote.reviewHard==='object'?remote.reviewHard:{};if(typeof remote.lastView==='string')S.lastView=remote.lastView;save(false);syncPulling=false;renderDiagnostics();renderModules();renderReviews();progress();if(['home','diag','mods','review','proof','jobs','data'].includes(S.lastView))view(S.lastView)}
function setSyncStatus(text,ok=false){const el=byId('syncStatus');if(!el)return;el.textContent=text;el.dataset.ok=ok?'1':'0'}
function fillSyncForm(){if(byId('syncUrl'))byId('syncUrl').value=syncCfg.url||'';if(byId('syncToken'))byId('syncToken').value=syncCfg.token||''}
function validApiUrl(url){try{const u=new URL(url);return u.protocol==='https:'||u.hostname==='localhost'||u.hostname==='127.0.0.1'}catch{return false}}
async function pullSync({quiet=false}={}){const base=normalizedApiUrl();if(!base||!syncCfg.token)return false;setSyncStatus('Sincronizando…');try{const res=await fetch(`${base}/v1/progress`,{headers:authHeaders()});if(!res.ok)throw new Error(`HTTP ${res.status}`);const data=await res.json();if(data.state){applyRemoteProgress(data.state);if(!quiet)toast('Progreso descargado del VPS.')}else{await pushSync({quiet:true});if(!quiet)toast('VPS conectado; subí tu progreso actual.')}syncReady=true;setSyncStatus(`Conectado · última sincronización ${new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}`,true);return true}catch(err){syncReady=false;setSyncStatus('Sin conexión. El progreso local sigue funcionando.');if(!quiet)toast('No pude conectar con el VPS.');return false}}
async function pushSync({quiet=false}={}){const base=normalizedApiUrl();if(!base||!syncCfg.token||syncPulling)return false;try{const res=await fetch(`${base}/v1/progress`,{method:'PUT',headers:authHeaders({'Content-Type':'application/json'}),body:JSON.stringify({state:syncState()})});if(!res.ok)throw new Error(`HTTP ${res.status}`);syncReady=true;setSyncStatus(`Sincronizado · ${new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}`,true);if(!quiet)toast('Progreso sincronizado.');return true}catch{syncReady=false;setSyncStatus('No se pudo subir. Guardado localmente.');if(!quiet)toast('No pude subir el progreso; quedó guardado en este dispositivo.');return false}}
function scheduleSync(){clearTimeout(syncTimer);syncTimer=setTimeout(()=>pushSync({quiet:true}),700)}
async function connectSync(){const url=byId('syncUrl').value.trim().replace(/\/+$/,''),token=byId('syncToken').value.trim();if(!validApiUrl(url)){toast('Usa una URL HTTPS válida para el VPS.');return}if(token.length<12){toast('El token parece demasiado corto.');return}syncCfg={url,token};localStorage.setItem(SYNC_CONFIG_KEY,JSON.stringify(syncCfg));await pullSync()}
function disconnectSync(){syncReady=false;syncCfg={};localStorage.removeItem(SYNC_CONFIG_KEY);fillSyncForm();setSyncStatus('No conectado. Tu progreso sigue guardado localmente.');toast('Sincronización desconectada de este dispositivo.')}
async function initSync(){fillSyncForm();if(syncCfg.url&&syncCfg.token)await pullSync({quiet:true});else setSyncStatus('No conectado. Configura tu VPS una sola vez por dispositivo.')}
function installSyncPanel(){const grid=document.querySelector('#data .dataGrid');if(!grid||byId('syncUrl'))return;const intro=document.querySelector('#data .pagehead p');if(intro)intro.textContent='El progreso puede sincronizarse automáticamente entre teléfono y computadora mediante tu VPS. El respaldo manual queda como plan B.';const card=document.createElement('article');card.className='dataCard';card.innerHTML=`<h3>Sincronización entre dispositivos</h3><p>Usa la misma URL y token en cada dispositivo. El curso descarga primero el estado del VPS y después sincroniza cada cambio.</p><label style="display:block;font-weight:800">URL del API<input id="syncUrl" type="url" inputmode="url" placeholder="https://curso-api.tudominio.com" autocomplete="url" style="width:100%;min-height:48px;border:1px solid var(--line);background:var(--bg);color:var(--ink);padding:10px;border-radius:0;margin:6px 0 12px"></label><label style="display:block;font-weight:800">Token privado<input id="syncToken" type="password" placeholder="token del VPS" autocomplete="off" style="width:100%;min-height:48px;border:1px solid var(--line);background:var(--bg);color:var(--ink);padding:10px;border-radius:0;margin:6px 0 12px"></label><div class="actions"><button class="primary" id="connectSync">conectar y sincronizar</button><button class="ghost" id="syncNow">sincronizar ahora</button><button class="danger" id="disconnectSync">desconectar</button></div><p id="syncStatus">No conectado.</p><small>El mismo servidor también genera audio en español de México para Brave cuando la voz del navegador falla.</small>`;grid.prepend(card)}
installSyncPanel();
$$('[data-view]').forEach(b=>b.addEventListener('click',()=>view(b.dataset.view)));
$$('[data-go]').forEach(b=>b.addEventListener('click',()=>view(b.dataset.go)));
byId('diagToRoute').addEventListener('click',()=>view('mods'));
byId('closeDialog').addEventListener('click',closeDialog);byId('dialog').addEventListener('click',e=>{if(e.target===byId('dialog'))closeDialog()});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeDialog()});
byId('themeBtn').addEventListener('click',()=>{S.prefs.dark=!S.prefs.dark;save(false);applyPrefs()});
byId('spaceBtn').addEventListener('click',()=>{S.prefs.wide=!S.prefs.wide;save(false);applyPrefs()});
byId('focusBtn').addEventListener('click',()=>{S.prefs.focus=!S.prefs.focus;save(false);applyPrefs();toast(S.prefs.focus?'Modo enfoque activado.':'Modo enfoque desactivado.')});
byId('fontBtn').addEventListener('click',()=>{const cur=Number(S.prefs.fs)||16;S.prefs.fs=cur>=22?16:cur+2;save(false);applyPrefs();toast(`Texto: ${S.prefs.fs}px`)});
$$('[data-mode]').forEach(b=>b.addEventListener('click',()=>{S.prefs.sessionMode=b.dataset.mode;save(false);applyPrefs();toast(`Modo: ${byId('modeLabel').textContent}`)}));
byId('timerStart').addEventListener('click',toggleTimer);byId('timerReset').addEventListener('click',resetTimer);
byId('exportBtn').addEventListener('click',exportBackup);byId('copyBtn').addEventListener('click',copyBackup);byId('importBtn').addEventListener('click',importBackup);byId('resetAll').addEventListener('click',resetAll);
byId('connectSync').addEventListener('click',connectSync);byId('syncNow').addEventListener('click',()=>pullSync());byId('disconnectSync').addEventListener('click',disconnectSync);
renderDiagnostics();renderModules();renderReviews();applyPrefs();progress();drawTimer();updateBackupText();
if(['home','diag','mods','review','proof','jobs','data'].includes(S.lastView))view(S.lastView);
initSync();
